name: game-session-service

services:
  game-session-service:
    container_name: game-session-service
    image: 'game-session-service:latest'
    ports:
      - "9098:9098"
    expose:
      - 9098
    depends_on:
      psql-game-session-service:
        condition: service_healthy
    environment:
      - POSTGRES_JDBC_URL=jdbc:postgresql://psql-game-session-service:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_PROFILES_ACTIVE=local

  psql-game-session-service:
    container_name: psql-game-session-service
    image: 'postgres:14.7'
    restart: always
    ports:
      - "5444:5432"
    expose:
      - 5444
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
